apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapUsers: |
    - groups:
        - system:masters
      userarn: arn:aws:iam::886436932371:user/github-ci
      username: github-ci